version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  api:
    build: .
    ports: 
      - 3030:3030
    environment:
      - PORT=3030
      - DATABASE_URL=db
    depends_on:
      - db
